### ISSUE TITLE
geckodriver.exe unable to start correctly

### ISSUE THREAD

**Issue by mandroid19** [Ahlyab/Udemy-coupon-fetcher.github.io#1]
First of all, thanks for the program. 
I tried to run every udemy exe (of the 3) but I get the same result:
geckodriver.exe - Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application.
I have also copied the VCRUNTIME140.dll into every folder, but nothing.

**Comment by Ahlyab** [comment]
Make sure you have installed firefox of latest version. 
Don't mess with files simply run udemy free coupons.exe.
